CREATE DATABASE IF NOT EXISTS hb_student_tracker;
USE hb_student_tracker;
DROP TABLE IF EXISTS Employee;
CREATE TABLE Employee (
id INT(6) NOT NULL AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(30) DEFAULT NULL,
lastname VARCHAR(30) DEFAULT NULL,
company VARCHAR(30) DEFAULT NULL
);